name: Publish a release containing compressed Go source code

on:
  push:

jobs:
  # Compress source code and upload it as an artifact
  compress_source_artifacts:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Compress source code
      - name: Compress source code
        run: |
          mkdir -p ./dist
          cd dist
          tar -czvf ./api ./go.mod ./go.sum ./LICENSE ./README.md

      # Upload Artifacts to be used in release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            ./dist/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs:
      - compress_source_artifacts

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts  # Download artifacts to this directory

      - name: Create package.json
        run: |
          echo '{"version": "1.0.0"}' > package.json

      - name: Install dependencies
        run: npm install --save-dev semantic-release @semantic-release/git @semantic-release/changelog

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      # Create a new release using the rules in .releaserc.yml
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        if: github.ref == 'refs/heads/main'